version: "3.7"
services:
    api:
      build: .
      ports:
        - 6000:6000
      environment:
        DB_URL: postgresql://postgres:admin1234@postgres:5432/starwars_dev
      volumes:
        - .:/startwar-api
      restart: on-failure
    postgres:
      image: postgres:13.2-alpine
      ports:
          - 5432:5432
      volumes:
          - ./postgresdata:/var/lib/postgresql/data
      restart: always
      environment:
        POSTGRES_PASSWORD: admin1234
        POSTGRES_USER: postgres
        POSTGRES_DB: starwars_dev
volumes:
 starwar: